baseurl = "https://flo.stellbr.ink"
languageCode = "en-us"
title = "Florian Stellbrink"
theme = "flo.stellbr.ink"
disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[permalinks]
    portfolio = "/portfolio/:slug"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/flostellbrink"
    weight = 2

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/flostellbrink/"
    weight = 2

[markup.goldmark.renderer]
    unsafe = true
